export const SETTINGS_FILE = "settings.json";

export const NVIDIA_API_URL = "https://integrate.api.nvidia.com/v1/chat/completions"
export const NVIDIA_API_KEY = import.meta.env.VITE_NVIDIA_API_KEY
export const MODEL = "mistralai/ministral-14b-instruct-2512"
export const COMMONLOCALES = [
  "af-ZA",
  "am-ET",
  "ar-SA",
  "be-BY",
  "bg-BG",
  "ca-ES",
  "cs-CZ",
  "da-DK",
  "de-DE",
  "el-GR",
  "en-US",
  "es-ES",
  "et-EE",
  "fa-IR",
  "fi-FI",
  "fr-FR",
  "he-IL",
  "hi-IN",
  "hr-HR",
  "hu-HU",
  "id-ID",
  "is-IS",
  "it-IT",
  "ja-JP",
  "ko-KR",
  "lt-LT",
  "lv-LV",
  "mk-MK",
  "ms-MY",
  "nb-NO",
  "nl-NL",
  "pl-PL",
  "pt-PT",
  "ro-RO",
  "ru-RU",
  "sk-SK",
  "sl-SI",
  "sq-AL",
  "sr-SP",
  "sv-SE",
  "th-TH",
  "tr-TR",
  "uk-UA",
  "vi-VN",
  "zh-CN",
];

